import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { cn } from "@/lib/utils";
import Main from "@/components/Main";

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Hype Dog",
  description: "Generated by create next app",
  icons: {
    icon: "/image1-transparent.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("", lato.className)}>
        {/* <Header />
        {children} */}
        <Main page={children} />
      </body>
    </html>
  );
}
